services:
  db:
    image: mysql:8
    container_name: ai-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ai_testing
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  backend:
    build: ./backend
    container_name: ai-backend
    environment:
      DB_URL: jdbc:mysql://db:3306/ai_testing
      DB_USER: root
      DB_PASSWORD: root
      JWT_SECRET: MySecretKey123
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  ai-engine:
    build: ./ai-engine
    container_name: ai-engine
    ports:
      - "5000:5000"

volumes:
  mysql-data:
